[package]
name = "world-time-api"
version = "1.0.0"
authors = ["Nicolas BAUW <nbauw@hotmail.com>"]
edition = "2018"
description = "A world time API. Dockerfile provided."
keywords = ["time", "world", "API"]
categories = ["date-and-time"]
license = "GPL-3.0"
repository = "https://github.com/nicolasbauw/world-time-api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
tzparse = { version = "1.0", features=["json"] }
