[package]
name = "world-time-api"
version = "0.1.7"
authors = ["Nicolas BAUW <nbauw@hotmail.com>"]
edition = "2018"
description = "A world time API. Dockerfile provided."
keywords = ["time", "world", "API"]
categories = ["date-and-time"]
license = "GPL-3.0"
repository = "https://github.com/nicolasbauw/world-time-api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde = "*"
serde_derive = "*"
serde_json = "1.0.40"
chrono = "0.4"
tzparse = "0.5.0"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]


