[package]
name = "time-api"
version = "0.1.0"
authors = ["Nicolas BAUW <nicolas.bauw@leroymerlin.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde = "*"
serde_derive = "*"
serde_json = "1.0.40"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]
